######################################################################
# Automatically generated by qmake (2.01a) Sat Sep 10 13:05:29 2011
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += mswipeextension.cpp

HEADERS += mswipeextension.h

target.path = /usr/lib/mcompositor
INSTALLS += target
