######################################################################
# Automatically generated by qmake (2.01a) Sat Sep 10 13:05:29 2011
######################################################################

TEMPLATE = lib
TARGET = $$qtLibraryTarget(meeswipe)
INCLUDEPATH += /usr/include

QT += opengl

# Input
SOURCES += mswipeextension.cpp swipemanagerextensionfactory.cpp

HEADERS += mswipeextension.h swipemanagerextensionfactory.h

target.path = /usr/lib/mcompositor
INSTALLS += target
